version: '2'

services:
    lucee:
        build:
            context: ./lucee
            args:
                - LUCEE_PASSWORD=${LUCEE_PASSWORD}
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ../:/var/www
            - ../var/log/tomcat:/usr/local/tomcat/logs
            - ../var/log/lucee:/opt/lucee/web/logs
            - ./lucee/root_home/.bash_history:/root/.bash_history
            - ../../../cfml/:/var/www/cfml
        ports:
            - "8887:8888"
        stdin_open: true
        tty: true
        networks:
            - backend

    postgres:
        build:
            context: ./postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - "5432:5432"
        volumes:
            - postgresData:/var/lib/postgresql/data
            - ./postgres/root_home:/root
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - database.backend

volumes:
    postgresData:

networks:
    backend:
        driver: "bridge"
